POST http://localhost:4004/user-service/updateUserStatus
Content-Type: application/json
Authorization: Basic admin admin

{
    "userID": "73b1e036-b7d0-447a-adc5-1df0b2d272ea", 
    "status": "Inactive"
}